# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js - Express Server - Test APIs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        mongodb-version: ['4.2']

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
      
    - name: Symlink for package-lock.json so next step is happy
      run: ln -s back-end/package-lock.json package-lock.json
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        
    - name: Import Mongo Records
      run: |
        cd back-end/mongo/schema
        mongoimport --db "COSE-Preparedness-Map" --collection "cose-maps"  --type "json" --file "cose-maps2.json"
    
    - name: Install Node Modules
      run: |
        cd back-end
        npm install
        
    - name: Run Tests
      run: |
        cd back-end
        npm test
